---
name: "Release"
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"
  workflow_dispatch:
permissions:
  contents: "write"
  packages: "write"
jobs:
  goreleaser:
    runs-on: "depot-ubuntu-24.04-4"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "authzed/actions/setup-go@main"
      - uses: "nowsprinting/check-version-format-action@v4"
        id: "version"
        with:
          prefix: "v"
      - name: "Fail for an invalid version"
        if: "${{ !startsWith(github.ref_name, 'v') || steps.version.outputs.is_valid != 'true' }}"
        run: 'echo "SpiceDB version must start with `v` and be a semver" && exit 1'
        shell: "bash"
      - name: "Install snapcraft"
        run: |
          sudo snap install snapcraft --channel=8.x/stable --classic
          mkdir -p $HOME/.cache/snapcraft/download
          mkdir -p $HOME/.cache/snapcraft/stage-packages
      - uses: "authzed/actions/docker-login@main"
        with:
          quayio_token: "${{ secrets.QUAYIO_PASSWORD }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          dockerhub_token: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
      - uses: "docker/setup-qemu-action@v3"
      - uses: "docker/setup-buildx-action@v3"
      - uses: "goreleaser/goreleaser-action@v6"
        with:
          distribution: "goreleaser-pro"
          # NOTE: keep in sync with goreleaser version in other job.
          # github actions don't allow yaml anchors.
          version: "v2.3.2"
          args: "release --clean"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          HOMEBREW_TAP_GITHUB_TOKEN: "${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}"
          GORELEASER_KEY: "${{ secrets.GORELEASER_KEY }}"
          GEMFURY_PUSH_TOKEN: "${{ secrets.GEMFURY_PUSH_TOKEN }}"
          SNAPCRAFT_STORE_CREDENTIALS: "${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}"
      - name: "Notify Slack of goreleaser status"
        if: "always()"
        uses: "slackapi/slack-github-action@v2.0.0"
        with:
          webhook: "${{ secrets.SLACK_WEBHOOK_URL }}"
          webhook-type: "incoming-webhook"
          payload: |
            text: "*Release Job Finished* with status: ${{ job.status }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    *Goreleaser Job* finished with status: ${{ job.status }}
                    *Repository:* <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>
                    *Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>
                    *Job Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Job Run>
                    *Actor:* ${{ github.actor }}
                    *Ref:* ${{ github.ref }}
                    *Workflow:* ${{ github.workflow }}
